### ISSUE TITLE
new version: no results

### ISSUE THREAD

**Issue by ronaldoviber** [Nhogs/popoto#51]
i installed the current version 2.0.17, but the queries copied form 2.0.11 doesn't work. 
No basic request work. 

Is there a special neo-version required?
What was changed?

**Comment by Popotojs** [comment]
Changes since 2.0.11 shouldn't break your existing application.

The examples on [popoto-examples](https://github.com/Nhogs/popoto-examples) are still all working using latest version of Popoto and no changes in their configuration since june 20, 2018.

There is no special Neo4j version required.

What are the errors you get in console?

If it's a connection issue you can try your database config and acces from this [notebook](https://beta.observablehq.com/@popotojs/popoto-js)

Since 2.0.11 the changes are detailed below and are mainly around negative constraints:

#43 : 2.0.12
minor change to avoir error in console with graph.rescale
#45 : 2.0.13
add support of multiple attributes in order by configuration in provider
#46 : 2.0.14
Refactoring of not constraint
#48 : 2.0.15 
add negative constraints in count and value queries
#49 : 2.0.16
add unit tests in query generation
#50 : 2.0.17
add arrow for reverse order relationships in query generation

**Comment by ronaldoviber** [comment]
mmhhm,
it´s the same VM, the same neo, but it doesn´t work
i try again with a fresh install
thanks for answering
btw. it´s a good work :))

**Comment by ronaldoviber** [comment]
every thing works fine, thank you

**Comment by Popotojs** [comment]
Cool, I close this issue then.
Let me know if you need more info.
