### ISSUE TITLE
Using local graph data with popoto.js

### ISSUE THREAD

**Issue by shoaib-jpeg** [Nhogs/popoto#75]
Hi everyone,

In my app I'm simply trying to display data from my neo4j database but am having some trouble understanding some things. I am aware that BOLT is not supported by popoto.js, so what I did was retrieve data using PHP and store the result locally. My question is, how do I use the local data I have stored and use it in my popoto visualization? The reason I'm confused is that I still need to provide a value for popoto.rest.CYPHER_URL even though I won't be using it. Thanks in advance.

Edit:
This is the query I'm using to retrieve data:
Match (n:Bay)-[r]->(m:Parts) Return n,r,m

When using this query, neoviz.js has no issue visualizing the data, so I was wondering how i can use the data retireved from running this query in popoto

**Comment by Popotojs** [comment]
Hi Popoto is now using BOLT through [Neo4j Javascript Drivers](https://github.com/Nhogs/popoto/wiki/Getting-started#define-the-neo4j-driver-to-connect-to-the-database)

It is not easy to use local data with Popoto because on each UI action cypher queries are runs to filter the results, it can be done without simulating a Neo4J server
